---

- name: Fetch Organisation Repositories
  ansible.builtin.include_tasks:
    file: common/http.yaml
  vars:
    in_check_mode: false
    url: "{{ lookup('env', 'GIT_API_URL') }}/orgs/{{ git_repo_owner }}/repos"
    validate_certs: "{{ lookup('env', 'GIT_API_VALIDATE_CERT') | default(true) }}"
    method: GET
    register_var: http_get_gitea_orgs_repos
    header_authorization: "Bearer {{ lookup('env', 'GIT_API_TOKEN') }}"
    json_body: {}


- name: Check if Repository Exists
  ansible.builtin.set_fact:
    repository_exists: |-
      {%- set ns = namespace( ignore_hosts= []) -%}
      {%- set ns.exists = false -%}
      {%- set repositories = http_get_gitea_orgs_repos.json | default([]) | list | length | int -%}

      {%- if repositories > 0 -%}
        {%- for org_repo in http_get_gitea_orgs_repos.json -%}
          {%- if org_repo.name | string == git_repo_name -%}
            {%- set ns.exists = true -%}
          {%- endif -%}
        {%- endfor %}
      {%- endif -%}
      {{ ns.exists }}


- name: Add a Repository
  ansible.builtin.include_tasks:
    file: common/http.yaml
  vars:
    url: "{{ lookup('env', 'GIT_API_URL') }}/orgs/{{ git_repo_owner }}/repos"
    validate_certs: "{{ lookup('env', 'GIT_API_VALIDATE_CERT') | default(true) }}"
    method: POST
    register_var: http_post_gitea_orgs_repos
    header_authorization: "Bearer {{ lookup('env', 'GIT_API_TOKEN') }}"
    json_body: "{{ git_gitea_create_repo_org }}"
  when: >
    not repository_exists
      and
    http_get_gitea_orgs_repos.status == 200

