---

- name: Check Configuration Matches
  ansible.builtin.set_fact:
    config_diff: |-
      {%- set ns = namespace( ignore_hosts= []) -%}
      {%- set ns.diff = {} -%}
      {%- set ns.is_correct = true -%}
      {%- for key, value in gitea_configuration_returned.items() -%}
        {%- if
          git_gitea_config[key] != value

        -%}
          {%- set ns.is_correct = false -%}
          {%- set ns.diff = ns.diff | combine({ key: {"actual": value, "expected": git_gitea_config[key] | default('-empty-')} }, recursive=True) -%}
        {%- endif -%}
      {%- endfor -%}
      {
        'is_correct': {{ ns.is_correct | bool }},
        'diff':  {{ ns.diff }}
      }
  changed_when: >-    # Set `changed_when` as `Add Repository Config` cant have it set
    not config_diff.is_correct


- name: Add Repository Config
  ansible.builtin.include_tasks:
    file: common/http.yaml
  vars:
    url: "{{ lookup('env', 'GIT_API_URL') }}/repos/{{ git_repo_owner }}/{{ git_repo_name }}"
    validate_certs: "{{ lookup('env', 'GIT_API_VALIDATE_CERT') | default(true) }}"
    method: PATCH
    register_var: http_patch_gitea_config
    header_authorization: "Bearer {{ lookup('env', 'GIT_API_TOKEN') }}"
    json_body: "{{ git_gitea_config }}"
  when:
    not config_diff.is_correct
