---

- name: Fetch Authenticated User
  ansible.builtin.include_tasks:
    file: common/http.yaml
  vars:
    in_check_mode: false
    url: "{{ lookup('env', 'GIT_API_URL') }}/user"
    validate_certs: "{{ lookup('env', 'GIT_API_VALIDATE_CERT') }}"
    method: GET
    register_var: http_get_gitea_user
    header_authorization: "Bearer {{ lookup('env', 'GIT_API_TOKEN') }}"
    json_body: {}
